In [1]:
import pandas as pd
import numpy as np

In [13]:
data = pd.read_csv('test.txt', sep=" ", skiprows=1, header=None, dtype = str)

In [14]:
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,Notification,handle,=,0x000e,value:,f9,8e,fb,89,01,00,19,01,NaN
1,Notification,handle,=,0x000e,value:,37,8f,00,8a,01,00,19,01,NaN
2,Notification,handle,=,0x000e,value:,76,8f,00,8a,01,00,19,01,NaN
3,Notification,handle,=,0x000e,value:,b4,8f,ff,89,01,00,19,01,NaN
4,Notification,handle,=,0x000e,value:,f3,8f,fc,89,01,00,18,01,NaN
5,Notification,handle,=,0x000e,value:,31,90,01,8a,01,00,18,01,NaN
6,Notification,handle,=,0x000e,value:,70,90,00,8a,01,00,18,01,NaN
7,Notification,handle,=,0x000e,value:,ae,90,fd,89,01,00,18,01,NaN
8,Notification,handle,=,0x000e,value:,ed,90,00,8a,01,00,18,01,NaN
9,Notification,handle,=,0x000e,value:,2b,91,fd,89,01,00,18,01,NaN

In [15]:
output_df = pd.DataFrame()
output_df["Hanldes"] = data[0] +" "+ data[1] +" " +data[2] +" "+ data[3] + data[4]
output_df["Timestamps (sec)"] = data[6] + data[5]
output_df["Pressure (mbar)"] = data[10] + data[9] + data[8] + data[7]
output_df["Temperature (degree C)"] = data[12] + data[11]

In [17]:
output_df["Timestamps (sec)"]  = [int(x, 16)/100 for x in  output_df["Timestamps (sec)"]]
output_df["Pressure (mbar)"]  = [int(x, 16)/100 for x in  output_df["Pressure (mbar)"]]
output_df["Temperature (degree C)"]  = [int(x, 16)/10 for x in  output_df["Temperature (degree C)"]]

In [18]:
output_df

,Hanldes,Timestamps (sec),Pressure (mbar),Temperature (degree C)
0,Notification handle = 0x000evalue:,366.01,1008.59,28.1
1,Notification handle = 0x000evalue:,366.63,1008.64,28.1
2,Notification handle = 0x000evalue:,367.26,1008.64,28.1
3,Notification handle = 0x000evalue:,367.88,1008.63,28.1
4,Notification handle = 0x000evalue:,368.51,1008.60,28.0
5,Notification handle = 0x000evalue:,369.13,1008.65,28.0
6,Notification handle = 0x000evalue:,369.76,1008.64,28.0
7,Notification handle = 0x000evalue:,370.38,1008.61,28.0
8,Notification handle = 0x000evalue:,371.01,1008.64,28.0
9,Notification handle = 0x000evalue:,371.63,1008.61,28.0

In [19]:
output_df.to_csv("test.csv", index = False)